name: qlevar_router
description: Manage you project Routes. Create nested routes. Simply navigation without context to your pages. Change only one sub widget in your page when navigating to new route.
version: 0.2.5
repository: https://github.com/SchabanBo/qlevar_router

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
